this["JST"] = this["JST"] || {};

this["JST"]["app/templates/fengshui"] = Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [2,'>= 1.0.0-rc.3'];
helpers = helpers || Handlebars.helpers; data = data || {};
  


  return "<div class=\"hero-unit\">\n    <form class=\"form-horizontal\">\n        <div class=\"input-append\">\n        <select>\n        <option selected=\"selected\" value=\"壬山丙向\">壬山丙向</option>\n        <option value=\"子山午向\">子山午向</option>\n        <option value=\"癸山丁向\">癸山丁向</option>\n        <option value=\"────\">────</option>\n        <option value=\"丑山未向\">丑山未向</option>\n        <option value=\"艮山坤向\">艮山坤向</option>\n        <option value=\"寅山申向\">寅山申向</option>\n        <option value=\"────\">────</option>\n        <option value=\"甲山庚向\">甲山庚向</option>\n        <option value=\"卯山酉向\">卯山酉向</option>\n        <option value=\"乙山辛向\">乙山辛向</option>\n        <option value=\"────\">────</option>\n        <option value=\"辰山戌向\">辰山戌向</option>\n        <option value=\"巽山乾向\">巽山乾向</option>\n        <option value=\"巳山亥向\">巳山亥向</option>\n        <option value=\"────\">────</option>\n        <option value=\"丙山壬向\">丙山壬向</option>\n        <option value=\"午山子向\">午山子向</option>\n        <option value=\"丁山癸向\">丁山癸向</option>\n        <option value=\"────\">────</option>\n        <option value=\"未山丑向\">未山丑向</option>\n        <option value=\"坤山艮向\">坤山艮向</option>\n        <option value=\"申山寅向\">申山寅向</option>\n        <option value=\"────\">────</option>\n        <option value=\"庚山甲向\">庚山甲向</option>\n        <option value=\"酉山卯向\">酉山卯向</option>\n        <option value=\"辛山乙向\">辛山乙向</option>\n        <option value=\"────\">────</option>\n        <option value=\"戌山辰向\">戌山辰向</option>\n        <option value=\"乾山巽向\">乾山巽向</option>\n        <option value=\"亥山巳向\">亥山巳向</option>\n\n        </select>\n        <select>\n            <option value=\"一运\">一运</option>\n            <option value=\"二运\">二运</option>\n            <option value=\"三运\">三运</option>\n            <option value=\"四运\">四运</option>\n            <option value=\"五运\">五运</option>\n            <option value=\"六运\">六运</option>\n            <option value=\"七运\">七运</option>\n            <option selected=\"selected\" value=\"八运\">八运</option>\n            <option value=\"九运\">九运</option>\n        </select>\n        <select>\n            <option value=\"挨星下卦\">挨星下卦</option>\n            <option value=\"挨星替卦\">挨星替卦</option>\n        </select>\n        <button type=\"submit\" class=\"btn btn-primary\">飞星</button>\n        \n        </div>\n    \n    </form>\n</div>";
  });